#!/usr/bin/env bash

set -o errexit \
    -o nounset \
    -o pipefail \
    -o noclobber

package_name="ANSYS"
package_version="2024.R1"
package_description="The Ansys suite provides a range of engineering-oriented physics simulation packages."
package_variant=""

source includes/source_includes.sh

# We need a newer version of the CXX ABI than RHEL7's base or GCC 4.9.2 provides.
module purge
module load gcc-libs

# Legacy install script
# This is a pre-built commercial product that doesn't really follow
#  a traditional unpack-and-build process, so there's not much to
#  be gained by making it strictly conform to one of our normal
#  patterns.

NAME=${package_name:-ANSYS}
VERSION=${package_version:-2024.R1}
INSTALL_VARIANT=${package_variant:-}
INSTALL_PREFIX=${INSTALL_PREFIX:-/shared/ucl/apps/${NAME}/${VERSION}${INSTALL_VARIANT:+-}${INSTALL_VARIANT}}
SRC_ARCHIVE=${SRC_ARCHIVE:-/shared/ucl/apps/ANSYS/installers/${VERSION}}
ELECTRONICS=${ELECTRONICS:-ELECTRONICS_2024R1_LINX64.tgz}
ELECTRONICS_ADD=${ELECTRONICS_ADD:-ELECTRONICS_2024R1.1_LINX64.tgz}
FLUIDSTRUCTURES=${FLUIDSTRUCTURES:-FLUIDSTRUCTURES_2024R1_LINX64.tgz}
PREPPOST=${PREPPOST:-PREPPOST_2024R1_LINX64.tgz}
CFXNODES=${CFXNODES:-/shared/ucl/apps/build_scripts/files/ANSYS/cfxnodes}
CFXNODES_CS=${CFXNODES_CS:-/shared/ucl/apps/build_scripts/files/ANSYS/cfxnodes_cs}


# Needs approx 60 GB to unpack so using ~/Scratch

archive_dir="$HOME/Scratch/Software/ANSYS/installers/$VERSION"
mkdir -p "$archive_dir"
cd "$archive_dir"

echo "Unpacking archives into $archive_dir ..."
mkdir -p ELECTRONICS
cd ELECTRONICS
tar -xvf "${SRC_ARCHIVE}/${ELECTRONICS}"
tar -xvf "${SRC_ARCHIVE}/${ELECTRONICS_ADD}"
cd ..
mkdir -p FLUIDSTRUCTURES
cd FLUIDSTRUCTURES
tar -xvf "${SRC_ARCHIVE}/${FLUIDSTRUCTURES}"
cd ..
mkdir -p PREPPOST
cd PREPPOST
tar -xvf "${SRC_ARCHIVE}/${PREPPOST}"
cd ..
echo "Archives unpacked."

mkdir -p "${INSTALL_PREFIX}/ucl/bin"
echo ""
echo "The first two installers run silently:"
echo ""
echo "$(pwd)/FLUIDSTRUCTURES/INSTALL"
echo "$(pwd)/PREPPOST/INSTALL"
echo ""
echo "FLUIDSTRUCTURES ..."
cd FLUIDSTRUCTURES
./INSTALL -nochecks -silent -install_dir "$INSTALL_PREFIX" -licserverinfo 2325:1055:lic-ansys.ucl.ac.uk 
# ./INSTALL
echo "PREPPOST ..."
cd ../PREPPOST
./INSTALL -nochecks -silent -install_dir "$INSTALL_PREFIX" -licserverinfo 2325:1055:lic-ansys.ucl.ac.uk

echo ""
echo "Now the Electronics package and patch..."
echo "These used to be run using the GUI installer, but in 2024.R1 we switched to the silent installer."
echo ""
echo "$(pwd)/ELECTRONICS/Electronics_241_linx64/install"
echo ""
echo "Use: $INSTALL_PREFIX/AnsysEM as the install location for ELECTRONICS."

echo "ELECTRONICS ..."
cd ../ELECTRONICS/Electronics_241_linx64
# Don't use the GUI installers
#./install
Linux/AnsysEM/Disk1/InstData/setup.exe -i silent \
    -DUSER_INSTALL_DIR="$INSTALL_PREFIX/AnsysEM" \
    -DTMP_DIR=/tmp \
    -DLICENSE_SERVER1=lic-ansys.ucl.ac.uk \
    -DSPECIFY_PORT=1 \
    -DLICENSE_PORT=1055 \

echo ""
echo "added installing the update patch here"
cd ../Electronics_24.1.1_linx64
./install_patch.bash --install_dir "$INSTALL_PREFIX/AnsysEM"

echo ""
echo "Installing UCL GE support scripts ..."
cp "$CFXNODES" "${INSTALL_PREFIX}/ucl/bin/cfxnodes"
cp "$CFXNODES_CS" "${INSTALL_PREFIX}/ucl/bin/cfxnodes_cs"
echo "Finished."

printf "\nNote that this script does not generate or store an Environment Module.\nPlease consult the existing modules for guidance.\n"

