#!/usr/bin/env bash

set -e

for i in ${includes_dir:=$(dirname $0 2>/dev/null)/includes}/{module_maker,require}_inc.sh; do . $i; done

require gcc-libs/10.2.0

YEAR=${YEAR:-2024}
RELEASE=${RELEASE:-24.5}
RELEASE_=$(echo $RELEASE | sed 's|\.||g')
NAME=${NAME:-nvhpc}
VERSION=${VERSION:-${YEAR}_${RELEASE_}}
INSTALL_PREFIX=${INSTALL_PREFIX:-/shared/ucl/apps/$NAME/$VERSION/$COMPILER_TAG}
MD5=${MD5:-be6059ea40ebf174bfee055cd714f186} # https://developer.download.nvidia.com/hpc-sdk/24.5/md5sum.txt

SRC_ARCHIVE=${SRC_ARCHIVE:-https://developer.download.nvidia.com/hpc-sdk/${RELEASE}/${NAME}_${VERSION}_Linux_x86_64_cuda_multi.tar.gz}


mkdir -p /scratch/$(whoami)/${NAME}

temp_dir=$(mktemp -d -p /scratch/$(whoami)/${NAME})

cd $temp_dir

wget $SRC_ARCHIVE
archive=$(basename "${SRC_ARCHIVE}")

md5sum -c <<< "$MD5 $archive" 


tar -xvf $archive

export NVHPC_INSTALL_DIR=${INSTALL_PREFIX}
export NVHPC_SILENT=true

echo $NVHPC_INSTALL_DIR

cd ${NAME}_${VERSION}_Linux_x86_64_cuda_multi
./install

rm -rf $temp_dir
